python3 cloud_manager.py \
	--project_id sinergym \
	--zone europe-west1-b \
	--template_name sinergym-experimental \
	--bucket_name ahmed-experiments \
	--group_name ahmed-evaluation \
	--experiment_commands \
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Mixed_LinRew_2022-05-28_10:51/PPO-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Mixed_LinRew_2022-05-28_10:51.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id PPO_Cont_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Cool_LinRew_2022-05-28_00:37/SAC-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Cool_LinRew_2022-05-28_00:37.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id SAC_Cont_Cool_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Hot_LinRew_2022-05-28_00:36/SAC-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Hot_LinRew_2022-05-28_00:36.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id SAC_Cont_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Mixed_LinRew_2022-05-28_00:36/SAC-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Mixed_LinRew_2022-05-28_00:36.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id SAC_Cont_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Cool_LinRew_2022-05-28_00:38/TD3-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Cool_LinRew_2022-05-28_00:38.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id TD3_Cont_Cool_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Hot_LinRew_2022-05-28_00:37/TD3-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Hot_LinRew_2022-05-28_00:37.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id TD3_Cont_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Mixed_LinRew_2022-05-28_00:38/TD3-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Mixed_LinRew_2022-05-28_00:38.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id TD3_Cont_Mixed_OccupRew'