python3 cloud_manager.py \
	--project_id sinergym \
	--zone europe-west1-b \
	--template_name sinergym-experimental \
	--bucket_name ahmed-experiments \
	--group_name ahmed-evaluation \
	--experiment_commands \
	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Hot_OccupRew_2022-05-31_20:09/SAC-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Hot_OccupRew_2022-05-31_20:09.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id SAC_Cont_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Mixed_OccupRew_2022-05-31_20:09/SAC-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Mixed_OccupRew_2022-05-31_20:09.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id SAC_Cont_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Cool_OccupRew_2022-05-31_20:10/SAC-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Cool_OccupRew_2022-05-31_20:10.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id SAC_Cont_Cool_OccupRew'\

	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Hot_OccupPropRew_2022-06-02_11:13/SAC-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Hot_OccupPropRew_2022-06-02_11:13.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id SAC_Cont_Hot_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Mixed_OccupPropRew_2022-06-02_11:13/SAC-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Mixed_OccupPropRew_2022-06-02_11:13.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id SAC_Cont_Mixed_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/SAC-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Cool_OccupPropRew_2022-06-02_11:14/SAC-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-SAC_Cont_Cool_OccupPropRew_2022-06-02_11:14.zip --episodes 5 --algorithm SAC --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id SAC_Cont_Cool_OccupPropRew'\



	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Hot_OccupRew_2022-06-01_13:22/TD3-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Hot_OccupRew_2022-06-01_13:22.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id TD3_Cont_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Mixed_OccupRew_2022-06-01_13:23/TD3-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Mixed_OccupRew_2022-06-01_13:23.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id TD3_Cont_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Cool_OccupRew_2022-06-01_13:23/TD3-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Cool_OccupRew_2022-06-01_13:23.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id TD3_Cont_Cool_OccupRew'\

	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Hot_OccupPropRew_2022-06-01_13:24/TD3-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Hot_OccupPropRew_2022-06-01_13:24.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id TD3_Cont_Hot_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Mixed_OccupPropRew_2022-06-01_13:54/TD3-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Mixed_OccupPropRew_2022-06-01_13:54.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id TD3_Cont_Mixed_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/TD3-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Cool_OccupPropRew_2022-06-01_13:54/TD3-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-TD3_Cont_Cool_OccupPropRew_2022-06-01_13:54.zip --episodes 5 --algorithm TD3 --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id TD3_Cont_Cool_OccupPropRew'\



	'python load_agent.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/A2C-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Hot_OccupRew_2022-06-01_20:00/A2C-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Hot_OccupRew_2022-06-01_20:00.zip --episodes 5 --algorithm A2C --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id A2C_Disc_Aug_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/A2C-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Mixed_OccupRew_2022-06-01_20:01/A2C-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Mixed_OccupRew_2022-06-01_20:01.zip --episodes 5 --algorithm A2C --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id A2C_Disc_Aug_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/A2C-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Cool_OccupRew_2022-06-01_20:01/A2C-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Cool_OccupRew_2022-06-01_20:01.zip --episodes 5 --algorithm A2C --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id A2C_Disc_Aug_Cool_OccupRew'\

	'python load_agent.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/A2C-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Hot_OccupPropRew_2022-06-01_20:02/A2C-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Hot_OccupPropRew_2022-06-01_20:02.zip --episodes 5 --algorithm A2C --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id A2C_Disc_Aug_Hot_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/A2C-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Mixed_OccupPropRew_2022-06-01_20:03/A2C-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Mixed_OccupPropRew_2022-06-01_20:03.zip --episodes 5 --algorithm A2C --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id A2C_Disc_Aug_Mixed_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/A2C-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Cool_OccupPropRew_2022-06-01_20:03/A2C-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-A2C_Disc_Aug_Cool_OccupPropRew_2022-06-01_20:03.zip --episodes 5 --algorithm A2C --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id A2C_Disc_Aug_Cool_OccupPropRew'\



	'python load_agent.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/DQN-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Hot_OccupRew_2022-06-01_18:41/DQN-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Hot_OccupRew_2022-06-01_18:41.zip --episodes 5 --algorithm DQN --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id DQN_Disc_Aug_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/DQN-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Mixed_OccupRew_2022-06-01_18:42/DQN-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Mixed_OccupRew_2022-06-01_18:42.zip --episodes 5 --algorithm DQN --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id DQN_Disc_Aug_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/DQN-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Cool_OccupRew_2022-06-01_18:42/DQN-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Cool_OccupRew_2022-06-01_18:42.zip --episodes 5 --algorithm DQN --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id DQN_Disc_Aug_Cool_OccupRew'\

	'python load_agent.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/DQN-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Hot_OccupPropRew_2022-06-01_18:43/DQN-Eplus-5Zone-hot-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Hot_OccupPropRew_2022-06-01_18:43.zip --episodes 5 --algorithm DQN --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id DQN_Disc_Aug_Hot_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/DQN-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Mixed_OccupPropRew_2022-06-01_18:44/DQN-Eplus-5Zone-mixed-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Mixed_OccupPropRew_2022-06-01_18:44.zip --episodes 5 --algorithm DQN --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id DQN_Disc_Aug_Mixed_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --model gs://ahmed-experiments/best_model/DQN-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Cool_OccupPropRew_2022-06-01_19:44/DQN-Eplus-5Zone-cool-discrete-stochastic-v1-episodes-20-seed-1-id-DQN_Disc_Aug_Cool_OccupPropRew_2022-06-01_19:44.zip --episodes 5 --algorithm DQN --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id DQN_Disc_Aug_Cool_OccupPropRew'\



	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Hot_OccupRew_2022-06-01_13:55/PPO-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Hot_OccupRew_2022-06-01_13:55.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id PPO_Cont_Hot_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Mixed_OccupRew_2022-06-01_17:36/PPO-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Mixed_OccupRew_2022-06-01_17:36.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id PPO_Cont_Mixed_OccupRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Cool_OccupRew_2022-06-01_17:37/PPO-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Cool_OccupRew_2022-06-01_17:37.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBased --remote_store --auto_delete --id PPO_Cont_Cool_OccupRew'\

	'python load_agent.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Hot_OccupPropRew_2022-06-01_17:37/PPO-Eplus-5Zone-hot-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Hot_OccupPropRew_2022-06-01_17:37.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id PPO_Cont_Hot_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Mixed_OccupPropRew_2022-06-01_17:38/PPO-Eplus-5Zone-mixed-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Mixed_OccupPropRew_2022-06-01_17:38.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id PPO_Cont_Mixed_OccupPropRew'\
	'python load_agent.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --model gs://ahmed-experiments/best_model/PPO-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Cool_OccupPropRew_2022-06-01_19:04/PPO-Eplus-5Zone-cool-continuous-stochastic-v1-episodes-20-seed-1-id-PPO_Cont_Cool_OccupPropRew_2022-06-01_19:04.zip --episodes 5 --algorithm PPO --normalization --logger --seed 1 --reward occupancyBasedProp --remote_store --auto_delete --id PPO_Cont_Cool_OccupPropRew'