python cloud_manager.py \
    --project_id sinergym \
    --zone europe-west1-b \
    --template_name sinergym-experimental \
    --bucket_name ahmed-experiments \
    --group_name ahmed-train \
    --experiment_commands \

# SAC (cont)
## Linear reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Cool_LinRew' \

## OccupancyBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Cool_OccupRew' \

## OccupancyProportionalBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Cool_OccupPropRew' \


# TD3 (cont)
## Linear reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Cool_LinRew' \

## OccupancyBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Cool_OccupRew' \

## OccupancyProportionalBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Cool_OccupPropRew' \


# A2C (disc)
## Linear reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Cool_LinRew' \

## OccupancyBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Cool_OccupRew' \

## OccupancyProportionalBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Cool_OccupPropRew' \


# PPO (cont)
## Linear reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Cool_LinRew' \

## OccupancyBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Cool_OccupRew' \

## OccupancyProportionalBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_lambda 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Cool_OccupPropRew' \



# DQN (disc)
## Linear reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Cool_LinRew' \

## OccupancyBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Cool_OccupRew' \

## OccupancyProportionalBased Reward
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://ahmed-experiments/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Cool_OccupPropRew'