python3 cloud_manager.py \
    --project_id sinergym \
    --zone europe-west1-b \
    --template_name sinergym-template \
    --group_name td-train \
    --experiment_commands \
### Action space discrete reduced ###
    # DQN
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Red_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Red_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Red_Reduced_LinRew' \
    # A2C
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Red_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Red_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Red_Cool_LinRew' \

### Action space discrete augmented ###
## Lineal Reward
    # DQN
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Cool_LinRew' \
    # A2C
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Cool_LinRew' \
## OccupancyBased Reward
    # DQN
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Cool_OccupRew' \
    # A2C
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Cool_OccupRew' \
## OccupancyProportionalBased Reward
    # DQN
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm DQN --learning_rate 0.0001 --buffer_size 1000000 --learning_starts 50000 --batch_size 32 --tau 1.0 --gamma 0.99 --gradient_steps 1 --max_grad_norm 10 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DQN_Disc_Aug_Cool_OccupPropRew' \
    # A2C
    'python DRL_battery.py --environment Eplus-5Zone-hot-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-discrete-stochastic-v1 --episodes 20 --algorithm A2C --learning_rate 0.0007 --n_steps 5 --gamma 0.99 --gae_lambda 1.0 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --rms_prop_eps 1e-05  --logger --log_interval 300 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id A2C_Disc_Aug_Cool_OccupPropRew' \



### Action space continuous ###
## Linear Reward
    # DDPG
#    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Hot_LinRew' \
#    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Mixed_LinRew' \
#    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Cool_LinRew' \
    
    # PPO
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Cool_LinRew' \

    # SAC
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Cool_LinRew' \
    
    # TD3
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Hot_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Mixed_LinRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward linear --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Cool_LinRew' \


## OccupancyBased Reward
    # DDPG
#    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Hot_OccupRew' \
#    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Mixed_OccupRew' \
#    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Cool_OccupRew' \
    
    # PPO
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Cool_OccupRew' \

    # SAC
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Cool_OccupRew' \
    
    # TD3
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Hot_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Mixed_OccupRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBased --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Cool_OccupRew' \



## OccupancyProportionalBased Reward
    # DDPG
#    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Hot_OccupPropRew' \
#    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Mixed_OccupPropRew' \
#    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm DDPG --learning_rate 0.001 --buffer_size 1000000 --learning_starts 100 --batch_size 100 --tau 0.005 --gamma 0.99 -1 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id DDPG_Cont_Cool_OccupPropRew' \
    
    # PPO
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm PPO --learning_rate 0.0001 --n_steps 4096 --batch_size 128 --n_epochs 15 --gamma 0.9 --gae_gamma 0.9 --clip_range 0.2 --ent_coef 0 --vf_coef 0.5 --max_grad_norm 0.5 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id PPO_Cont_Cool_OccupPropRew' \

    # SAC
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm SAC --learning_rate 0.0003 --buffer_size 1000000 --batch_size 256 --tau 0.005 --gamma 0.99 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id SAC_Cont_Cool_OccupPropRew' \
    
    # TD3
    'python DRL_battery.py --environment Eplus-5Zone-hot-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Hot_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-mixed-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Mixed_OccupPropRew' \
    'python DRL_battery.py --environment Eplus-5Zone-cool-continuous-stochastic-v1 --episodes 20 --algorithm TD3 --learning_rate 0.003 --buffer_size 1000000 --batch_size 64 --tau 0.005 --gamma 0.9 --logger --log_interval 1 --seed 1 --evaluation --eval_freq 4 --eval_length 3 --reward occupancyBasedProp --tensorboard gs://experiments-storage/tensorboard_log --remote_store --mlflow_store --normalization --auto_delete --id TD3_Cont_Cool_OccupPropRew'
